### ISSUE TITLE
incompatible with resources plugin 1.0.RC3+

### ISSUE THREAD

**Issue by verglor** [paulfairless/grails-lesscss-resources#1]
Since version 1.0.RC3 of resources plugin the following exception is thrown during app startup:

ERROR plugins.DefaultGrailsPluginManager  - Error configuring dynamic methods for plugin [resources:1.0.RC3]: Resource mapper lesscss must have a phase property defined
java.lang.IllegalArgumentException: Resource mapper lesscss must have a phase property defined
    at org.grails.plugin.resource.mapper.ResourceMapper$_getPhase_closure4.doCall(ResourceMapper.groovy:29)

**Comment by paulfairless** [comment]
version 0.3 now supports resources plugin 1.0+
