### ISSUE TITLE
Update to less 1.2.1

### ISSUE THREAD

**Issue by benatwork99** [paulfairless/grails-lesscss-resources#12]
I'm using the lesscss-resources plugin on an application with the Bootstrap framework, and the recent 2.0 GA release of Bootstrap requires features from a newer version of LESS. See https://github.com/twitter/bootstrap/issues/952 as an example where 1.2.1 is recommended.

Is it possible to update the less.js used by the plugin? I had a quick look and see the asual lesscss-engine component is being used but it appears to be using a rhino variant of less.js which doesn't have a version number. Should I post this issue to the lesscss-engine project?

**Comment by paulfairless** [comment]
This is provided by lesscss-engine, however looking at their github, work on 1.2.1 is underway. You can probably add the dependancy directly to your app once it's available, if you need it quickly:

<code>runtime 'com.asual.lesscss:lesscss-engine:1.2.1'</code>
