### ISSUE TITLE
Fatal error reloading less files after upgrade to 1.0

### ISSUE THREAD

**Issue by verglor** [paulfairless/grails-lesscss-resources#13]
After upgrade from 0.6.1 to 1.0 reloading no longer works for me. The following messages appears in the console and I have to restart server since grails is unable to render gsp:

```
ERROR ResourceMeta         - Resource not found: /css/styles_less.css
WARN  ResourceProcessor    - Cannot locate resource [/css/styles_less.css]
```

**Comment by paulfairless** [comment]
Hi,

Yeah, there was an issue with the fix for css processing and new reloading mechanism in the latest resources. 1.0.1 uses an alternative fix and works with the latest resources
