### ISSUE TITLE
Engine needs update

### ISSUE THREAD

**Issue by jameskleeh** [paulfairless/grails-lesscss-resources#15]
I attempted to use the .less files from twitter bootstrap and received many syntax errors that do not occur when I compile the same files with less-1.3.0.js. Can you update the engine to the newest version to support the latest syntax?

Apparently a few days after I posted this where was an update https://github.com/paulfairless/grails-lesscss-resources/commit/56519082853099d8088569ed79cb4d7e4dc33c4c

**Comment by paulfairless** [comment]
now updated to 1.3.1
