### ISSUE TITLE
Upgrade to version v1.1.3 of lesscss-engine

### ISSUE THREAD

**Issue by laufzeit** [paulfairless/grails-lesscss-resources#2]
Please upgrade the plugin to the current version of the lesscss-engine due to the following issue: 
https://github.com/asual/lesscss-engine/issues/7#issuecomment-1593460

**Comment by paulfairless** [comment]
although the code is updated there is no official release of 1.1.6 on asual yet. I'll keep track and update asap

**Comment by laufzeit** [comment]
thx. would be great to use your official plugin version. i currently replaced the less.js myself in the jar.

**Comment by paulfairless** [comment]
updated in version 0.4
