### ISSUE TITLE
Resources not found after compiling by Rhino

### ISSUE THREAD

**Issue by hanphony** [paulfairless/grails-lesscss-resources#21]
I am having trouble with the plugin. Everything seemed fine but after running the app in dev env, the page loads up but complains that it can't find the compiled css file. I am using Grails 2.0.1 and lesscss-resources 1.3.0.

Here is what I have in UiResources.groovy:

styling {
    defaultBundle 'styling'

```
resources url: '/less/mainStyles.less', attrs:[rel: "stylesheet/less", type: 'css'], disposition: 'head', bundle: 'bundle_styling'
resources url: '/css/other.css', disposition: 'head'
```

}

What shows up on the page is this:

< link href="/appName/bundle-bundle_styling_head.css" type="text/css" media="screen, projection" rel="stylesheet" >

Although I can locate this file in the ~/.grails/2.0.1/projects/appName/tomcat/worl/Tomcat/localhost/appName/grails-resources ...

Grails console also complains:

Resources not found: /bundle-bundle_styling_head.css

I have been trying different things to get this to work till no avail. Did I do anything wrong here?

**Comment by OverZealous** [comment]
I don't know _why_ it's broken, but if you remove the explicit `bundle: 'bundle_styling'`, it should work.  There appears to be a bug in the way the plugin handles bundles.
