### ISSUE TITLE
On Grails 2.0.x, the bundle declaration in the config doesn't work

### ISSUE THREAD

**Issue by nvinet** [paulfairless/grails-lesscss-resources#24]
Hi,

While using the latest grails ans resource version I discovered the the bundle declaration for each less resource breaks the compilation. Removing it work like a charm:

Doesn't work
'style' {
        resource url:'less/test.less',attrs:[rel: "stylesheet/less", type:'css'], bundle:'bundle_style'
    }

Works
'style' {
        resource url:'less/test.less',attrs:[rel: "stylesheet/less", type:'css']
    }

Don;t know if it is a change in Grails 2.0 / Resource 1.6 but might want to add a mention in the oc as it took me ages to figured it out.

**Comment by mathpere** [comment]
Hi,

Why this issue is closed? The issue is still there with grails 2.0.3 and resources 1.1.6 and your solution saved my time :-)

Regard.
