### ISSUE TITLE
LESS files do not get converted to CSS in debug mode

### ISSUE THREAD

**Issue by behrangsa** [paulfairless/grails-lesscss-resources#34]
I sometimes want to use `debugMode=true` to see the output of LESS CSS files prior to being compressed, but at the moment when I add  `debugMode=true` to the URL, I see the LESS files sent back verbatim to the browser.

**Comment by paulfairless** [comment]
when debugMode=true no resource processors run, so it does not have the chance to compile the .less files.

Ideally the .less files could be compiled  client side by including the less js compiler http://lesscss.org/. However this does not work due the the resources framework not allowing me to set rel="stylesheet/less" in debug mode
