### ISSUE TITLE
Change from Asual LESS compiler?

### ISSUE THREAD

**Issue by cplim** [paulfairless/grails-lesscss-resources#41]
Hi,

Is there a reason why there was a move away from the Asual LESS compiler to the LessCss-java compiler?  Comparing v1.3.0 of both compilers, the Asual version seems to be twice as fast as the other one.  

regards,
CP

**Comment by paulfairless** [comment]
Asual LESS compiler was not updated to 1.3.0 for a long time after it was available. This and it was hosted on their own maven repository which caused problems for several people.

The good news is version 1.3.1 should be faster, especially for bigger projects

**Comment by verglor** [comment]
Unfortunately [lesscss-java](https://github.com/marceloverdijk/lesscss-java) project seems to be [abandoned](https://github.com/marceloverdijk/lesscss-java/issues/13) in contrast to assual [lesscss-engine](https://github.com/asual/lesscss-engine) which updated to 1.3.3 recently and also has consistent versioning with less.js
