### ISSUE TITLE
Different grail less plugins

### ISSUE THREAD

**Issue by Vad1mo** [paulfairless/grails-lesscss-resources#43]
Hello, 

I starting to use twitter bootstrap with less and I found 3 different grails Plugins for less.
1. less-resources (recommended by twitter-bootstrap Plugin team)
2. lesscss 
3. lesscss-resources (this one! based on 2 + resourcess)

I would like to know what is the difference between Plugin 1 and 3. Is Plugin 3 compatible with twitter-bootstrap Plugin? What is the reason there are 2 Plugins doing the same?

I posted almost the same question to less-resources team https://github.com/groovydev/less-grails-plugin/issues/7 

cheers,
V.

**Comment by paulfairless** [comment]
less-resources is custom built for the twitter-bootstrap plugin.

This plugin uses standard implementations, and although it works with twitter-bootstap, I do not know if it works with the twitter-bootstap grails plugin.

**Comment by Vad1mo** [comment]
I now checked out both plugins and as far as I can see observing the results and the code they are pretty much the same. Both work  with the twitter bootstrap plugin. (With a lot of limitations!  e.g. A reference like @import bootstrap.less is not allowed/fails because file can't be found )
