### ISSUE TITLE
README "Usage" section is inadequate

### ISSUE THREAD

**Issue by nickdos** [paulfairless/grails-lesscss-resources#46]
In the "Usage" section of the README file, it provides an example snippet of groovy code but fails to tell the user where this code needs to be added. Please provide an explicit instruction on where to include this code. 

Furthermore, I was not able to get a simple example working with some LESS files. It would be helpful to provide the minimum amount of config & GSP code to get up and running. Note, I have no experience using the Resources plugin, which I'm guessing is assumed knowledge.

**Comment by paulfairless** [comment]
I understand your point - however a complete example would require some duplication of the Resources documentation. The config in question can be applied in several different places.

The Resources mechanism is a core part of Grails and will remain assumed knowledge. I I receive similar feedback I will reconsider.

Thanks
