### ISSUE TITLE
Problem with referenced images

### ISSUE THREAD

**Issue by vgrichina** [paulfairless/grails-lesscss-resources#5]
When I reference image in LESS stylesheet, it doesn't work. Like in this example:

```
    background: url('../images/header-pattern.png');
```

I believe CSS processing by resources plugin works fine in such case, but LESS doesn't.

**Comment by paulfairless** [comment]
It's working fine for me in a simple case. Can you provide a test scenario for me to investigate further (less file, resources config). 

do you have any other resource plugins installed?

**Comment by vgrichina** [comment]
See my stylesheets and images here.

http://minus.com/mepQNlVL6

Less stylesheet is referenced like this:

```
    <r:external uri="/css/public.less" type="css" />
```

I have no resources config, do I need to make it to resolve problem?

**Comment by vgrichina** [comment]
I have no other resource plugins installed, just standard Grails 2.0-M2 + LessCSS Resources (latest from GitHub)

**Comment by paulfairless** [comment]
i can replicate this issue with the r:external - it may be a problem with the resources plugin, as opposed to lesscss-resources specifically - but i need to investigate further.

for now you could work around the issue by defining the file in a resource bundle (which does correctly resolve image paths)- details can be found in the docs

**Comment by vgrichina** [comment]
Thanks, workaround worked for me.

**Comment by tixxit** [comment]
I can confirm this too. However, it doesn't happen for all images (!?). I am not using r:external, but the resources DSL.

**Comment by verglor** [comment]
I have the same problem and I am also using resources DSL, however when building war all images are bundled.

My workaround is adding the following to my resources module:

```
new File('web-app/images').traverse(type: groovy.io.FileType.FILES) {
    resource url: "images${it.toString().replace('\\', '/') - 'web-app/images'}"
}
```

**Comment by paulfairless** [comment]
I've fixed an issue that was preventing some css processors to run, hopefully this will have fixed most of the issues experienced .

**Comment by verglor** [comment]
I can confirm the fix works for me. Thank You!

**Comment by tixxit** [comment]
Seems to have fixed the problem for me as well. Thanks!
