### ISSUE TITLE
Better handling of @import at dev-time needed

### ISSUE THREAD

**Issue by delight** [paulfairless/grails-lesscss-resources#9]
Hi,

as the changes on imported less files (@import) are not triggering a rebuild of the resource, 
I think it would be a better solution to use the client side js-compile at dev time as a workaround
.
So the output should look something like:

<link rel="stylesheet/less" href="/path/to/mystyle.less">

<script src="/path/to/less.js"></script>

Even thou this would be "just" a workaround, I think this is an important change, 
to make the development with the less css resource plugin feel more grails-like.

Cheers,
   Kosta

**Comment by ghost** [comment]
I would also really like to see some way to have imported files automatically reloaded

**Comment by cweekly** [comment]
try livereload.app for osx
